language: node_js

node_js:
- '10'

services:
- docker

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin hub.sotaleb.ch

script:
  - docker build -t hub.sotaleb.ch/abcd/abcd:latest . && docker push hub.sotaleb.ch/abcd/abcd:latest