language: node_js

node_js:
- '10'

services:
- docker

before_install:
  - curl -fsSL https://deno.land/x/install/install.sh | sh
  - ~/.deno/bin/deno test --allow-all

before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin hub.sotaleb.ch

script:
  - TAG=$([ "$TRAVIS_TAG" == "" ] && echo "latest" || echo "$TRAVIS_TAG")
  - docker build -t hub.sotaleb.ch/abcd/abcd:$TAG --no-cache . && docker push hub.sotaleb.ch/abcd/abcd:$TAG