language: node_js

node_js:
- '10'

services:
- docker

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin hub.sotaleb.ch

jobs:
  include:
    - stage: build
      name: "Build Docker image"
      script: docker build -t hub.sotaleb.ch/abcd/abcd:latest .
    - stage: deploy
      name: "Deploy Docker image"
      script: docker push hub.sotaleb.ch/abcd/abcd:latest