version: "3.8"
services:
    master:
        image: deno
        volumes:
            - "~/Code/abcd/:/app"
        ports:
            - "8080:8080"
        command:
            - "deno"
            - "run"
            - "--unstable"
            - "--allow-write"
            - "--allow-net"
            - "--allow-read"
            - "main.ts"
            - "--debug"
    first_follower:
        image: deno
        volumes:
            - "~/Code/abcd/:/app"
        depends_on:
            - "master"
        command:
            - "deno"
            - "run"
            - "--unstable"
            - "--allow-write"
            - "--allow-net"
            - "--allow-read"
            - "main.ts"
            - "--join"
            - "master"
            - "--debug"
    second_follower:
        image: deno
        volumes:
            - "~/Code/abcd/:/app"
        depends_on:
            - "master"
        command:
            - "deno"
            - "run"
            - "--unstable"
            - "--allow-write"
            - "--allow-net"
            - "--allow-read"
            - "main.ts"
            - "--join"
            - "master"
            - "--debug"